language: objective-c

install:
 - bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
 - source $HOME/.gvm/scripts/gvm
 - gvm install go1.3 --binary || gvm install go1.3
 - gvm use go1.3
 - export GOPATH=~
 - export PATH=$GOPATH/bin:$PATH
 - mkdir -p ~/src/github.com
 - mv ../../rjeczalik ~/src/github.com
 - cd ~/src/github.com/rjeczalik/pkgconfig
 - go version
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -t -v ./...
 - go install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
